on:
  workflow_run:
    workflows: [scenario-server]
    types: [completed]
  push:
    paths:
      - dotnet/**
      - .github/workflows/dotnet.yaml
  pull_request:
    paths:
      - dotnet/**
      - .github/workflows/dotnet.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1.x'

      - working-directory: ./dotnet/EasyRacer.Tests
        run: |
          dotnet test
