on:
  workflow_run:
    workflows: [scenario-server]
    types: [completed]
  push:
    paths:
      - java-loom/**
      - .github/java-loom.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - run: ./gradlew test
        working-directory: ./java-loom
