on:
  workflow_run:
    workflows: [scenario-server]
    types: [completed]
  push:
    paths:
      - kotlin-coroutines/**
      - .github/workflows/kotlin-coroutines.yaml
  pull_request:
    paths:
      - kotlin-coroutines/**
      - .github/workflows/kotlin-coroutines.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - run: ./gradlew test
        working-directory: ./kotlin-coroutines
