on:
  workflow_run:
    workflows: [scenario-server]
    types: [completed]
  push:
    paths:
      - python-aiohttp/**
      - .github/workflows/python-aiohttp.yaml
  pull_request:
    paths:
      - python-aiohttp/**
      - .github/workflows/python-aiohttp.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - working-directory: ./python-aiohttp
        run: |
          ulimit -n 16000
          nix-shell --run "pytest"
