on:
  workflow_run:
    workflows: [scenario-server]
    types: [completed]
  push:
    paths:
      - python-aiohttp-taskgroup/**
      - .github/workflows/python-aiohttp-taskgroup.yaml
  pull_request:
    paths:
      - python-aiohttp-taskgroup/**
      - .github/workflows/python-aiohttp-taskgroup.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - working-directory: ./python-aiohttp-taskgroup
        run: |
          curl -L -o - https://github.com/mitsuhiko/rye/releases/latest/download/rye-x86_64-linux.gz | gunzip > /tmp/rye
          chmod +x /tmp/rye
          export PATH=~/.rye/shims:$PATH
          /tmp/rye sync
          ulimit -n 16000
          /tmp/rye run pytest
