on:
  workflow_run:
    workflows: [scenario-server]
    types: [completed]
  push:
    paths:
      - python-httpx-asyncio/**
      - .github/workflows/python-httpx-asyncio.yaml
  pull_request:
    paths:
      - python-httpx-asyncio/**
      - .github/workflows/python-httpx-asyncio.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: ./python-httpx-asyncio/.python-version
          cache: 'pip'
          cache-dependency-path: ./python-httpx-asyncio/requirements.txt

      - working-directory: ./python-httpx-asyncio
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - working-directory: ./python-httpx-asyncio
        run: pytest
