on:
  workflow_run:
    workflows: [scenario-server]
    types: [completed]
  push:
    paths:
      - python-httpx-trio/**
      - .github/workflows/python-httpx-trio.yaml
  pull_request:
    paths:
      - python-httpx-trio/**
      - .github/workflows/python-httpx-trio.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixos-unstable=channel:nixos-unstable:nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - working-directory: ./python-httpx-trio
        run: nix-shell --run "pytest"
