on:
  workflow_run:
    workflows: [scenario-server]
    types: [completed]
  push:
    paths:
      - scala-ox/**
      - .github/workflows/scala-ox.yaml
  pull_request:
    paths:
      - scala-ox/**
      - .github/workflows/scala-ox.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21-ea'
          cache: 'sbt'

      - run: ./sbt test
        working-directory: ./scala-ox
