on:
  workflow_run:
    workflows: [scenario-server]
    types: [completed]
  push:
    paths:
      - scala-ce3/**
      - .github/workflows/scala-ce3.yaml
  pull_request:
    paths:
      - scala-ce3/**
      - .github/workflows/scala-ce3.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'sbt'

      - run: ./sbt ci:test
        working-directory: ./scala-ce3
