name: scenario-server

on:
  push:
    paths:
      - scenario-server/**
      - .github/workflows/scenario-server.yaml
  pull_request:
    paths:
      - scenario-server/**
      - .github/workflows/scenario-server.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'sbt'

      - name: Run tests
        working-directory: ./scenario-server
        run: ./sbt test

  build-and-push-amd64:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,suffix=-amd64
            type=raw,value=latest-amd64,enable={{is_default_branch}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          context: ./scenario-server
          file: ./scenario-server/Dockerfile-amd64
          push: ${{ github.actor == github.repository_owner }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-and-push-aarch64:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,suffix=-aarch64
            type=raw,value=latest-aarch64,enable={{is_default_branch}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64/v8
          context: ./scenario-server
          file: ./scenario-server/Dockerfile-aarch64
          push: ${{ github.actor == github.repository_owner }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  create-manifests:
    runs-on: ubuntu-latest
    if: ${{ github.actor == github.repository_owner }}
    needs: [build-and-push-amd64, build-and-push-aarch64]

    steps:
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create SHA manifest and push
        run: |
          docker buildx imagetools create \
            -t ${{ steps.meta.outputs.tags }} \
            ${{ steps.meta.outputs.tags }}-amd64 \
            ${{ steps.meta.outputs.tags }}-aarch64

      - name: Create latest manifest and push
        if: github.ref == 'refs/heads/main'
        run: |
          docker buildx imagetools create \
            -t ghcr.io/${{ github.repository }}:latest \
            ghcr.io/${{ github.repository }}:latest-amd64 \
            ghcr.io/${{ github.repository }}:latest-aarch64
