on:
  workflow_run:
    workflows: [scenario-server]
    types: [completed]
  push:
    paths:
      - swift-async/**
      - .github/workflows/swift-async.yaml
  pull_request:
    paths:
      - swift-async/**
      - .github/workflows/swift-async.yaml

jobs:
  test:
    runs-on: macos-latest
    if: ${{ github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - uses: docker-practice/actions-setup-docker@master

      - run: swift test -c release
        working-directory: ./swift-async
