on:
  workflow_run:
    workflows: [scenario-server]
    types: [completed]
  push:
    paths:
      - swift-combine/**
      - .github/workflows/swift-combine.yaml
  pull_request:
    paths:
      - swift-combine/**
      - .github/workflows/swift-combine.yaml

jobs:
  test:
    runs-on: macos-latest
    if: ${{ github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker on macOS
        uses: douglascamata/setup-docker-macos-action@v1-alpha

      - run: swift test -c release
        working-directory: ./swift-combine
